eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: projetService
            uri: http://localhost:8020
            predicates:
              - Path=/api/projets/**
          - id: ressourceService
            uri: http://localhost:8010
            predicates:
              - Path=/api/ressources/**
          - id: tacheService
            uri: http://localhost:8030
            predicates:
              - Path=/api/taches/**